name: "e2e"
on: [push]
jobs:
 test-e2e:
  name: Run E2E tests
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Install dependencies
      run: nmp ci
    - name: Install Playwright
      run: npx Playwright install --with-deps
    - name: Run your tests
      run: npx playwright test tests/home.spec.ts
    - name: GitHub Actions Version Updater
      uses: saadmk11/github-actions-version-updater@v0.8.1